version: '3'
services:
  wordpress:
    container_name: Wordpress
    image: wordpress
    volumes:
      - './:/var/www/html'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  mysql:
    container_name: mysql
    image: hypriot/rpi-mysql
    volumes:
      - './data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  redis:
    image: redis
    container_name: redis
volumes:
    mysql: null
    wordpress: null
